name: VeteBacin
description: A sample ChatGPT client built with Flutter.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dart_openai: ^1.8.0
  flutter:
    sdk: flutter
  markdown_widget: ^2.0.0+1
  flutter_markdown: ^0.6.14
  mysql1: ^0.19.2
  sql_conn: ^0.0.3
  fluttertoast: ^8.2.1
  http: ^0.13.5
  intl: ^0.17.0
  country_state_city_picker: ^1.2.8
  country_state_city_pro: ^0.0.3
  shared_preferences: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/vetebacinlogo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/background_login.png
    - assets/images/background_login2.png
    - assets/images/35bG11.png
    - assets/images/35bG22.png
    - assets/images/37Logoo.png
    - assets/images/37Logoo_.png
    - assets/images/37Logoo_2.png
    - assets/images/38bgbg.png
    - assets/images/38bgbgbg.png
    - assets/images/39loginbg.png
    - assets/images/39loginbg1.png
    - assets/images/39loginbg2.png
    - assets/images/39loginbg22.png
    - assets/images/38bgbgbg2.png
    - assets/images/38bgbgbg22.png
    - assets/images/38chatback.png
    - assets/images/chatbackground.png
    - assets/images/chatbackgr2.png
    - assets/images/vetebacinlogo.png